# Generated by Django 2.2.7 on 2019-12-02 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isDeleted',
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=4000)),
                ('salary', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
                ('userADMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
