# Generated by Django 2.2.7 on 2019-12-04 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191202_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
                ('jobVacancyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JobVacancy')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
