# Generated by Django 2.2.7 on 2019-11-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191129_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
