# Generated by Django 2.2.7 on 2019-12-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=3000)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField()),
                ('jobApplicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JobApplication')),
                ('userADMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
