# Generated by Django 2.2.7 on 2019-12-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191204_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
