# Generated by Django 2.2.7 on 2019-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191204_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleteDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
