# Generated by Django 2.2.7 on 2019-12-05 05:17

from django.db import migrations, models
import website.cpfvalidator


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191204_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, validators=[website.cpfvalidator.validate_CPF]),
        ),
    ]
